### PR TITLE
Find inner text for nested html

### PR DESCRIPTION
**Pull request by vyshakhj**
Noticed that the inner text does not work as expected for nested html. This PR will address that issue.

### CODE REVIEW

**Comment by maxhumber** [comment]
Actually, I don't think this is right.

`soup.text` should find:

```python
html = '<div>hi</div>'
Soup(html).text
'hi'

html = '<div><div>hi</div></div>'
Soup(html).text
''

html = '<div>hi<div>bye</div></div>'
Soup(html).text
'hi'

html = '<div><div>hi</div>bye</div>'
Soup(html).text
'bye'
```

**Comment by maxhumber** [comment]
With that said, I think you're in a really good position to solve #34 if you're willing? (Really appreciate all your work, it's been tremendously valuable)

**Comment by vyshakhj** [comment]
Does this `<div><div>hi</div></div>`  have to return an empty string? 

And yes, I could work on #34. Could you please assign it to me?

**Comment by maxhumber** [comment]
I think so. I would return empty in your example

**Comment by vyshakhj** [comment]
Makes sense. I think I can now work on #34 if it does not have an assignee yet.

**Pull request merged**
