### PR TITLE
Proper mocking for test_get

### LINKED ISSUE #37: Help with mocking network (get) tests
**Is your feature request related to a problem? Please describe.**

Right now gazpacho has to hit various websites in it's test suite to make sure everything works, including:

- https://en.wikipedia.org/
- https://httpbin.org/
- https://httpstat.us/

**Describe the solution you'd like**

These tests should really be mocked.

**Additional context**

Could use some help on doing this properly!

### PR DESCRIPTION
**Pull request by saibot94**
closes #37 

I had to move `get.py` to somewhere else because it was impossible to patch things inside it as there was already a `get` in `__init__.py`

### CODE REVIEW

**Review by maxhumber — COMMENTED** [review]
Thanks for all the mocking! I'm just not super clear on why get had to move? I'd like to keep things flat (and have it remain in a get.py file)

**Comment by saibot94** [comment]
The `patch("gazpacho.get.build_opener")` would not work, because you already have a relative import in the `__init__.py` file of the package. Whenever I try to do the patch above it's trying to mock the function in `__init__.py`.

The actual error:

```
 AttributeError: <function get at 0x000002347612B820> does not have the attribute 'build_opener'
```

 A quick search yielded the [following answer](https://stackoverflow.com/a/6630415). To make it work, I moved `get.py` into another package. 

Another alternative would be to rename `get.py` or the `get` function to something else. What would you suggest?

**Comment by saibot94** [comment]
Hi @maxhumber, in the end I found a way to perform the mock properly on the flat structure, please have another look!

**Comment by maxhumber** [comment]
Awesome work! Will merge :)

**Pull request merged**
