### PR TITLE
Error fixed file added

### LINKED ISSUE #28: .text is empty on Soup creation
**Describe the bug**

When I create a soup object...

**To Reproduce**

Calling .text returns an empty string:

```python
from gazpacho import Soup

html = """<p>&pound;682m</p>"""

soup = Soup(html)
print(soup.text)
''
```

**Expected behavior**

Should output:

```python
print(soup.text)
'£682m'
```

**Environment:**
 - OS: macOS
 - Version: 1.1

**Additional context**

Inspired by this [S/O question](https://stackoverflow.com/questions/2087370/decode-html-entities-in-python-string)

### PR DESCRIPTION
**Pull request by DeepanshuGOYAL05**
Hey, I have added Errorfixed.py. Please check iot 
Fixes #28

### CODE REVIEW

**Review by maxhumber — COMMENTED** [review]
Appreciate the effort, but I was more looking for something that changed the underlying source code so that `Soup(html).text` would work automatically/flawlessly.

**Comment by DeepanshuGOYAL05** [comment]
You can add my code in your main code. It would work I think so!!

**Comment by maxhumber** [comment]
Happy to merge if you are able to change the *underlying* way Soup represents .text to fix the issue on a *generalized* basis!

**Comment by maxhumber** [comment]
For example, ask if will your solution work with:

```python
html = """<div>hi</div>"""
soup = Soup(html)
assert soup.text == "hi"
```

**Comment by DeepanshuGOYAL05** [comment]
Can you provide me in detail what do you want basically?

**Comment by DeepanshuGOYAL05** [comment]
html1 = """<div>hi</div>"""
soup1 = Soup(html1)
res1=soup1.find('div')
print(res1.text)

#this will work for this

**Comment by DeepanshuGOYAL05** [comment]
`html1 = """<div>hi</div>"""
soup1 = Soup(html1)
res1=soup1.find('div')
print(res1.text)`

**Comment by DeepanshuGOYAL05** [comment]
Hey, is this solved?

**Pull request closed without merging**
